environment:
    matrix:
        - TOXENV: py27

init:
- ps: $zipPath = "$env:TEMP\PortableGit-2.11.1-64-bit.7z.exe"
- ps: (New-Object Net.WebClient).DownloadFile('https://github.com/git-for-windows/git/releases/download/v2.11.1.windows.1/PortableGit-2.11.1-64-bit.7z.exe', $zipPath)
- ps: 7z x $zipPath -aoa -o'C:\Program Files\Git' bin
- git --version

install:
    - "SET PATH=C:\\Python36;C:\\Python36\\Scripts;%PATH%"
    - pip install tox virtualenv --upgrade

# Not a C# project
build: false

test_script: tox

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.pre-commit'
