environment:
    matrix:
        - TOXENV: py27

init:
- git --version
- git config --global --add core.longpaths true

install:
    - "SET PATH=C:\\Python36;C:\\Python36\\Scripts;%PATH%"
    - pip install tox virtualenv --upgrade

# Not a C# project
build: false

test_script: tox

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.pre-commit'
